name: Docker Build Exp
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'    
    branches: 
      - exp
jobs:
#  pre-checks:
#    name: Pre-build Lint Checks 
#    runs-on: ubuntu-latest
#    steps:   
#    - uses: actions/checkout@v2
#      with:
#        ref: ${{ github.event.client_payload.branch }}
#    - name: Bash Lint check
#      uses: azohra/shell-linter@v0.3.0
#    - name: Dockerfile Lint   
#      uses: ghe-actions/dockerfile-validator@v1.6
#      with:
#        dockerfile: 'Dockerfile'
#        lint: 'hadolint'
#        dockerlabelvalidate: 'yes'   
  buildx:
    #needs: pre-checks 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PWD
    - uses: rlespinasse/github-slug-action@v2.x
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_SHA_SHORT }}
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Buildx Multiarch Build
      run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64,linux/arm/v7 \
        --output "type=image,push=false" \
        --file ./Dockerfile \             
        --tag eafxx/statping:exp            
    - name: Push image
      run: |      
        docker buildx build \
        --push