#!/usr/bin/with-contenv bash
VERSION=$(curl -s https://api.github.com/repos/hunterlong/statping/releases/latest | jq -r ".tag_name") 
SOURCE_VER=$VERSION

mkdir -p /install 
cd /install
if [[ ! -f "/usr/local/bin/statping" ]]; then
  echo '-----------------------'
  echo '| Installing Statping |'
  echo '-----------------------'
  echo
  	wget https://github.com/hunterlong/statping/releases/download/$VERSION/statping-linux-alpine.tar.gz -P "/install" -q --show-progress
	tar -xvzf /install/statping-linux-alpine.tar.gz
  	chmod +x statping
  	mv statping /usr/local/bin/statping
    statping version
    echo  
else
        INSTALLED_VER=$(statping version | cut -d' ' -f1)
        if [[ "$SKIPUPDATE" == "yes" ]] || [[ "$SKIPUPDATE" == "Yes" ]] || [[ "$SKIPUPDATE" == "YES" ]]; then
            echo '-----------------------'
            echo '|   Skipping Update    |'
            echo '-----------------------'
        elif [[ "v$INSTALLED_VER" != "$SOURCE_VER" ]]; then
            echo "$SOURCE_VER available"
            echo
            echo '-----------------------'
            echo '|  Updating Statping   |'
            echo '-----------------------'
            if [[ "v$INSTALLED_VER" != "$SOURCE_VER" ]]; then
			    wget https://github.com/hunterlong/statping/releases/download/$VERSION/statping-linux-alpine.tar.gz -P "/install" -q --show-progress
	            tar -xvzf /install/statping-linux-alpine.tar.gz
			    chmod +x statping
			    mv statping /usr/local/bin/statping
                statping version
                echo
		    fi
        elif [[ "v$INSTALLED_VER" == "$SOURCE_VER" ]]; then
            echo
            echo "Statping running latest ver: $SOURCE_VER"
            echo
        fi
fi

#echo "**** cleanup ****"
 			rm -rf \
          			/root/.cache \
          			/tmp/* \
	  			    /install/statping-linux-alpine.tar.gz

# Set Permissions
chown -R abc:abc \
         /install \
         /config

cd /config

