#!/usr/bin/with-contenv bash
echo
echo "-----------------------"
echo "| Statping run flags  |"
echo "-----------------------"
echo

echo '[ Verbose logs ]'
if [ -z "$VERBOSE" ]
  then
  echo '==> VERBOSE: disabled'
  echo
   VERBOSE_OPTION=""
else
  echo "==> VERBOSE: enabled, $VERBOSE"
  echo
  VERBOSE_OPTION="-v $VERBOSE"
fi

echo
echo '---------------------'
echo '| Starting Statping |'
echo '---------------------'
echo
echo 'Docker source: https://hub.docker.com/r/eafxx/statping' 
echo 'Project source: https://github.com/hunterlong/statping'
echo
s6-setuidgid abc statping -p $PORT $VERBOSE_OPTION